### ISSUE TITLE
Support for BF.INSERT command

### ISSUE THREAD

**Issue by ms10398** [RedisBloom/redisbloom-go#6]
Hey really excited to see the module in golang finally.

But was going to use it in my project but couldn't find the INSERT command which I wanted  to use.

Would be great if you could add that or I might take that up if required

**Comment by filipecosta90** [comment]
Hi there @ms10398, thank you for the message. Do you want to kick off the support of [BF.INSERT](https://oss.redislabs.com/redisbloom/Bloom_Commands/#bfinsert) it and we review/push it with you?

**Comment by ms10398** [comment]
Sure @filipecosta90 I would love to do it would be sending off the PR by tomorrow

**Comment by dengliming** [comment]
@ms10398 Hi~ Are you still flow this issue?

**Comment by ms10398** [comment]
Yes sorry got stuck up in lot of stuff will send off a PR today/tomorrow

**Comment by ms10398** [comment]
@filipecosta90 @dengliming can you guys go ahead was stuck with some issues

**Comment by dengliming** [comment]
@ms10398 Please feel free to submit a PR.

**Comment by dengliming** [comment]
@ms10398 May I ask if you will continue this PR. If not, I will submit it by the way.

**Comment by ms10398** [comment]
@dengliming can you please go forward as suggested by the above comment

**Comment by dengliming** [comment]
@ms10398 Sure. Will submit the PR today later. And Welcome to share your opinion. : )

**Comment by filipecosta90** [comment]
hi there @ms10398, #21 added `BF.INSERT` support. Thank you guys for raising this up and thank @dengliming for opening the PR with the fix :+1:
